### ISSUE TITLE
new Installation of mmm-shelly-pm: Errors and

### ISSUE THREAD

**Issue by SteBloch** [stefanjacobs/MMM-Shelly-PM#1]
I installed the module and did the configuration.
But when i restart the magic mirror the PI is overheating and overloaded.
The consumption data for a day is working, but the actual power not.
When i open the path of the sensor "http://192.168.0.149/rpc/Shelly.GetStatus" in my browser i see the datas from the Shelly-PM.

Do you have an Idea what the problem is?
Below you find my logs.
I have installed: magicmirror@2.21.0 at a raspberry 3b+.

**mm-error.log:**
[06.03.2023 19:46.45.532] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[06.03.2023 19:46.45.533] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[06.03.2023 19:46.45.560] [ERROR] Whoops! There was an uncaught exception...
[06.03.2023 19:46.45.565] [ERROR] Error: undefined is not a valid uri or options object.
    at request (/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_modules/request/index.js:44:11)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_helper.js:30:4)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:108:11)
    at Socket.emit (node:events:526:28)
    at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:475:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at process.processImmediate (node:internal/timers:437:9)

**mm-out.log:**
[06.03.2023 19:46.55.660] [LOG]   Error: ETIMEDOUT
    at Timeout.<anonymous> (/home/pi/MagicMirror/modules/MMM-Shelly-PM/node_modules/request/request.js:848:19)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7) {
  code: 'ETIMEDOUT',
  connect: true

**Comment by ghost** [comment]
I have exactly the same problem with the same error. Have you found any solution?

**Comment by torth** [comment]
Same issue within my installation. 
Exact same mm-error.log output

**Comment by thobach** [comment]
I believe there is a bug in https://github.com/stefanjacobs/MMM-Shelly-PM/blob/master/MMM-Shelly-PM.js#L30 where the variable should be called `self.config.ShellyApiPath` and not `self.config.uri`.
See also https://github.com/stefanjacobs/MMM-Shelly-PM/issues/2 for setting the right refresh interval variable name in the config.
I only have a Shelly PRO 3EM and cannot fully test the logic for Shelly PM devices.

**Comment by stefanjacobs** [comment]
Thank you for the report and sorry for the late reply, I will look into this.

**Comment by stefanjacobs** [comment]
Fixed, if anyone is still reading here ;-)
